from typing import Any, Dict


def safe_parse_llm_output(raw: Any) -> Dict[str, Any]:

    if raw is None:
        return _empty()

    # if string → convert to structured format
    if isinstance(raw, str):

        text = raw.strip()

        return {
            "title": text.split("\n")[0][:80],
            "description": text,
            "steps": [
                "generated by LLM",
                "parsed safely",
                "rendered to UI"
            ],
            "files": []
        }

    # if dict → ensure safe schema
    if isinstance(raw, dict):
        return {
            "title": raw.get("title", "AI Result"),
            "description": raw.get("description", ""),
            "steps": raw.get("steps") or ["generated"],
            "files": raw.get("files", [])
        }

    return _empty()


def _empty():
    return {
        "title": "No Result",
        "description": "",
        "steps": [],
        "files": []
    }